[package]
name = "pixelvault"
version = "0.1.0"
edition = "2024"

[dependencies]
aes-gcm = "0.10.3"
argon2 = "0.5.3"
chrono = "0.4.43"
eframe = "0.33.3"
egui-toast = "0.19.1"
rand = "0.9.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
